-- AUTOMATICALLY GENERATED -- DO NOT EDIT!

ABILITY_INFO_BLOODELF1 = "- 附魔技能提高。";
ABILITY_INFO_BLOODELF2 = "- 可以从敌人身上抽取法力值。";
ABILITY_INFO_BLOODELF4 = "- 对魔法伤害有天然抗性。";
ABILITY_INFO_BLOODELF3 = "- 可以使附近的敌人沉默。";
ABILITY_INFO_DRAENEI1 = "- 珠宝加工技能提高。";
ABILITY_INFO_DRAENEI2 = "- 可以持续治疗自己或其他人。";
ABILITY_INFO_DRAENEI3 = "- 队友的近战攻击和法术命中率提高。";
ABILITY_INFO_DRAENEI4 = "- 对暗影有天然抗性。";
ABILITY_INFO_DWARF1 = "- 可以变为石头形态。";
ABILITY_INFO_DWARF2 = "- 提高枪械武器技能。";
ABILITY_INFO_DWARF3 = "- 对冰霜伤害有抗性。";
ABILITY_INFO_DWARF4 = "- 寻找财宝。";
ABILITY_INFO_GNOME1 = "- 可挣脱各种减速效果的影响。";
ABILITY_INFO_GNOME2 = "- 提高智力属性。";
ABILITY_INFO_GNOME3 = "- 对奥术伤害有抗性。";
ABILITY_INFO_GNOME4 = "- 提高工程学技能。";
ABILITY_INFO_HUMAN1 = "- 侦测潜行的能力提高。";
ABILITY_INFO_HUMAN2 = "- 提高精神属性。";
ABILITY_INFO_HUMAN3 = "- 提高声望获得速度。";
ABILITY_INFO_HUMAN4 = "- 提高剑系和锤系武器技能。";
ABILITY_INFO_NIGHTELF1 = "- 可以遁入阴影中。";
ABILITY_INFO_NIGHTELF2 = "- 提高躲闪几率。";
ABILITY_INFO_NIGHTELF3 = "- 死后变成小精灵形态。";
ABILITY_INFO_NIGHTELF4 = "- 对自然伤害有抗性。";
ABILITY_INFO_ORC1 = "- 可狂暴，以受到治疗时的回复能力换取伤害力。";
ABILITY_INFO_ORC2 = "- 对昏迷效果有更高的抵抗能力。";
ABILITY_INFO_ORC3 = "- 提高宠物的伤害。";
ABILITY_INFO_ORC4 = "- 提高斧系武器技能。";
ABILITY_INFO_SCOURGE1 = "- 可对魅惑、催眠和恐惧免疫。";
ABILITY_INFO_SCOURGE2 = "- 可以通过吞食尸体回复生命值。";
ABILITY_INFO_SCOURGE3 = "- 延长水下呼吸时间。";
ABILITY_INFO_SCOURGE4 = "- 对暗影伤害有抗性。";
ABILITY_INFO_TAUREN1 = "- 可以践踏并震昏周围的敌人。";
ABILITY_INFO_TAUREN2 = "- 提高生命值上限。";
ABILITY_INFO_TAUREN3 = "- 提高草药学技能。";
ABILITY_INFO_TAUREN4 = "- 对自然伤害有抗性。";
ABILITY_INFO_TROLL1 = "- 狂暴，提高攻击施法速度。";
ABILITY_INFO_TROLL2 = "- 提高回复速度。";
ABILITY_INFO_TROLL3 = "- 提高对野兽的伤害。";
ABILITY_INFO_TROLL4 = "- 提高投掷武器和弓类武器技能。";
ACCEPT = "同意"; -- Generic "accept"
ACCOUNT_CREATE_FAILED = "账号创建失败";
ACCOUNT_CREATE_IN_PROGRESS = "创建账号";
ACCOUNT_CREATE_SUCCESS = "账号创建成功";
ACCOUNT_CREATE_URL = "http://signup.wowchina.com";
ACCOUNT_MESSAGE_BODY_URL = "http://www.wowchina.com/accountmessaging/getMessageBody.xml"; -- used by the account messaging system to retrieve the body of a message
ACCOUNT_MESSAGE_HEADERS_URL = "http://www.wowchina.com/accountmessaging/getMessageHeaders.xml"; -- used for the account messaging to query the list of message headers
ACCOUNT_NAME = "账号名称";
ACCOUNT_OPTIONS = "账号选项";
ADDONS = "插件";
ADDONS_OUT_OF_DATE = "您正在运行较新版本的游戏，并且您所用的某些插件已经过期。建议禁止加载这些插件。";
ADDON_BANNED = "禁用";
ADDON_CORRUPT = "损坏";
ADDON_DEPENDENCIES = "依赖功能：";
ADDON_DEP_BANNED = "依赖功能禁用";
ADDON_DEP_CORRUPT = "依赖功能损坏";
ADDON_DEP_DISABLED = "依赖功能被禁用";
ADDON_DEP_INCOMPATIBLE = "Dependency incompatible";
ADDON_DEP_INSECURE = "依赖功能不可靠";
ADDON_DEP_INTERFACE_VERSION = "依赖功能过期";
ADDON_DEP_MISSING = "依赖功能缺失";
ADDON_DISABLED = "禁用";
ADDON_FORCE_LOAD = "加载过期插件";
ADDON_INCOMPATIBLE = "Incompatible";
ADDON_INSECURE = "不可靠";
ADDON_INTERFACE_VERSION = "版本错误";
ADDON_LIST = "插件列表";
ADDON_SECURE = "安全";
ADDON_UPDATE_AVAILABLE = "新版本可用";
AGI = "敏捷"; -- G-15 Abbriviation for 'Agility'
ALL = "全部";
ALLIANCE = "联盟";
ALPHA_BUILD = "Alpha版本";
AMMO = "弹药%d"; -- G-15 Abbriviation for 'Ammunition' as in Ammunition count (number of hunter bullets)
ARM = "护甲"; -- G-15 Abbriviation for 'Armor'
ARMOR = "护甲";
ASSERTIONS_ENABLED_BUILD = "发行声明已激活";
AUTH_ALREADY_LOGGING_IN = "已经登录";
AUTH_ALREADY_ONLINE = "该角色仍在登录。若该角色无法登录且该状况持续超过15分钟，请访问tech@wowchina.com联系我们的技术支持部门。";
AUTH_BAD_SERVER_PROOF = "无效的服务器";
AUTH_BANNED = "该账号因违反用户协议条款－www.wowchina.com/termsofuse.shtml而被禁止。请发送电子邮件至wowaccountadmin@wowchina.com联系我们的GM部门获取更多信息。";
AUTH_BANNED_URL = "http://www.wowchina.com/termsofuse.shtml";
AUTH_BILLING_ERROR = "支付系统错误";
AUTH_BILLING_EXPIRED = "账号支付过期";
AUTH_DB_BUSY = "该会话已超时。请稍后再试或访问www.wowchina.com查看WoW服务器状态。";
AUTH_DB_BUSY_URL = "http://www.wowchina.com";
AUTH_FAILED = "验证失败";
AUTH_INCORRECT_PASSWORD = "密码错误";
AUTH_LOGIN_SERVER_NOT_FOUND = "无效的登录服务器";
AUTH_NO_TIME = "您的魔兽世界缴费已到期。您需要重新激活您的账号。要重新激活账号，请访问www.wowchina.com获取更多信息。";
AUTH_NO_TIME_URL = "http://www.wowchina.com/account/";
AUTH_OK = "验证成功";
AUTH_PARENTAL_CONTROL = "该账号已被账号冷冻器锁定。请访问http://www.wowchina.com获得更多信息。";
AUTH_PARENTAL_CONTROL_URL = "http://www.wowchina.com/";
AUTH_REJECT = "访问被拒绝 - 请通过tech@wowchina.com联系我们的客户支持人员";
AUTH_SERVER_SHUTTING_DOWN = "服务器正在关闭";
AUTH_SESSION_EXPIRED = "通话超时";
AUTH_SUSPENDED = "该账号因违反用户协议条款－www.wowchina.com/termsofuse.shtml而被暂停。请发送电子邮件至wowaccountadmin@wowchina.com联系我们的GM部门获取更多信息。";
AUTH_SUSPENDED_URL = "http://www.wowchina.com/termsofuse.shtml";
AUTH_SYSTEM_ERROR = "系统错误";
AUTH_UNAVAILABLE = "系统无法接入 - 请稍候再试";
AUTH_UNKNOWN_ACCOUNT = "未知账号";
AUTH_VERSION_MISMATCH = "错误的客户端版本";
AUTH_WAIT_QUEUE = "队列位置：%d";
AVAILABLE_CLASSES = "可以选择的职业";
BACK = "后退"; -- Generic "back"
BAG_SLOTS = "栏位%d"; -- G-15 Number of free bag slots
BATTLEFIELD_ALERT = "你可以进入%s了 你将在%s内被移出队列"; -- G-15
BETA_BUILD = "版本";
BF_DEATHS = "死亡"; -- G-15 Number of Deaths
BF_HONOR_KILLS = "荣誉击杀"; -- G-15 Number of kills
BF_HONOR_POINTS = "荣誉"; -- G-15 Amount of Honor
BF_KILLBLOWS = "击杀"; -- G-15 Killing blows
BF_NOT_IN = "你目前不在战场中"; -- G-15
BF_RANK = "等级"; -- G-15
BILLING_FIXED_IGR = "您正在使用固定IGR付费方式。您的个人时间不会被扣除。该方式付费期将在%s内结束。";
BILLING_FIXED_LASTDAY = "您的固定计划付费游戏账号将在一天之内过期。请到充值页面续费。";
BILLING_FREE_TIME_EXPIRE = "免费账号即将过期。过期之后您即将被断开连接。\n剩余时间%s";
BILLING_GAMEROOM_EXPIRE = "正在使用的IGR账号即将过期。过期之后您即将被断开连接。\n请联系您的IGR主管。";
BILLING_HAS_FALLBACK_PAYMENT = "您的账号上可能有通过其它支付方式获得的额外游戏时间。";
BILLING_IGR_USAGE = "您正在使用固定IGR按量计费方式。您的个人时间不会被扣除。";
BILLING_IGR_USAGE_TIME_LEFT_30_MINS = "IGR付费方式下的游戏时间少于30分钟。";
BILLING_TEXT1 = "您正在付费继续使用这个账号。当这个账号的游戏时间少于一天时，我们会通知您。";
BILLING_TEXT2 = "您正在免费游戏期，不会被扣除游戏时间";
BILLING_TEXT3 = "您正在使用个人付费方式进行游戏，该付费方式将在%s后过期。";
BILLING_TEXT4 = "您正在使用个人时间进行游戏，将在%d分钟后过期。您将在游戏时间结束之前的30分钟得到通知。";
BILLING_TIME_LEFT_30_MINS = "您的账号还有最多30分钟的游戏时间，请访问我们的充值页面并购买更多游戏时间。";
BILLING_TIME_LEFT_DAYS = "您的账号中还有%d天的剩余游戏时间";
BILLING_TIME_LEFT_LAST_DAY = "您的账号中的剩余游戏时间少于1天";
BLIZZ_DISCLAIMER = "版权所有 2004-2007 暴雪娱乐。保留所有权利。";
BLOCK = "BLOCK %.2f"; -- G-15
BONUS_DAMAGE = "B.DMG %d"; -- G-15 Abbriviation for Bonus Damage
BONUS_HEALING = "B.HEAL %d"; -- G-15 Abbriviation for Bonus Healing
BURNING_CRUSADE = "燃烧的远征";
CALCULATING = "正在计算…";
CANCEL = "取消"; -- Generic "cancel"
CATEGORY_DESCRIPTION = "服务器分类";
CATEGORY_DESCRIPTION_TEXT = "服务器位置是指其所在的地理位置。我们建议玩家选择距离他们最近的服务器，以获得最低的延迟和最好的游戏体验。";
CHANGE = "改变";
CHANGE_REALM = "选择服务器";
CHARACTER_CREATE_ACCEPT = "同意";
CHARACTER_NAME = "角色名称";
CHARACTER_SELECT_INFO = "等级%d %s";
CHARACTER_SELECT_INFO_GHOST = "等级%d %s（幽灵）";
CHAR_CREATE_ACCOUNT_LIMIT = "该账号允许的角色数量已达最大值。";
CHAR_CREATE_DISABLED = "现在无法创建该种族和/或职业的角色";
CHAR_CREATE_ERROR = "创建角色错误";
CHAR_CREATE_EXPANSION = "必须将账号升级为资料片账号之后才能创建该种族的角色。";
CHAR_CREATE_FAILED = "角色创建失败";
CHAR_CREATE_INVALID_NAME = "非法的角色名字";
CHAR_CREATE_IN_PROGRESS = "正在创建角色";
CHAR_CREATE_NAME_IN_USE = "此名字无法使用";
CHAR_CREATE_ONLY_EXISTING = "只有已经在这个服务器上创建了角色的玩家才能创建新角色。";
CHAR_CREATE_PVP_TEAMS_VIOLATION = "您在PvP服务器上所创建的所有角色必须属于同一个阵营";
CHAR_CREATE_SERVER_LIMIT = "该服务器允许的角色数量已达最大值。";
CHAR_CREATE_SERVER_QUEUE = "这个服务器目前已有玩家排队等待进入，新角色创建功能已被暂时禁止。请在非高峰时段重试。";
CHAR_CREATE_SUCCESS = "角色创建成功";
CHAR_CREATE_UNKNOWN = "未知错误";
CHAR_CUSTOMIZATION0_DESC = "性别";
CHAR_CUSTOMIZATION1_DESC = "肤色";
CHAR_CUSTOMIZATION2_DESC = "脸型";
CHAR_CUSTOMIZATION3_DESC = "发型";
CHAR_CUSTOMIZATION4_DESC = "发色";
CHAR_CUSTOMIZATION5_DESC = "胡须";
CHAR_CUSTOMIZATION6_DESC = "装束";
CHAR_DELETE_FAILED = "角色删除失败";
CHAR_DELETE_FAILED_LOCKED_FOR_TRANSFER = "你的角色正在进行付费转移，并暂时被锁定。";
CHAR_DELETE_IN_PROGRESS = "正在删除角色";
CHAR_DELETE_SUCCESS = "角色已经删除";
CHAR_LIST_FAILED = "角色列表获取错误";
CHAR_LIST_RETRIEVED = "角色列表获取成功";
CHAR_LIST_RETRIEVING = "获取角色列表";
CHAR_LOGIN_DISABLED = "您所选择的种族、职业或者角色无法登录。";
CHAR_LOGIN_DUPLICATE_CHARACTER = "您所选择的角色名称已经存在";
CHAR_LOGIN_FAILED = "登录失败";
CHAR_LOGIN_IN_PROGRESS = "正在进入魔兽世界";
CHAR_LOGIN_LOCKED_BY_BILLING = "角色已被锁定。请联系客服人员以获取更多信息。";
CHAR_LOGIN_LOCKED_FOR_TRANSFER = "您的角色正在进行付费转移，并暂时被锁定。";
CHAR_LOGIN_NO_CHARACTER = "未发现角色"; -- Most likely moved by migration tool but still in server cache
CHAR_LOGIN_NO_INSTANCES = "没有可以连接的服务器";
CHAR_LOGIN_NO_WORLD = "世界服务器无法连接";
CHAR_LOGIN_SUCCESS = "登录成功";
CHAR_NAME_FAILURE = "非法的角色名字";
CHAR_NAME_INVALID_APOSTROPHE = "您不能将省略号作为您的姓或名";
CHAR_NAME_INVALID_CHARACTER = "名字只能包含字符";
CHAR_NAME_INVALID_SPACE = "您不能使用空格作为名字的第一个字符或最后一个字符";
CHAR_NAME_MIXED_LANGUAGES = "名字中只能包含一种语言的文字";
CHAR_NAME_MULTIPLE_APOSTROPHES = "您只能使用一个省略号";
CHAR_NAME_NO_NAME = "请为您的角色输入一个名字";
CHAR_NAME_PROFANE = "此名字包含亵渎性内容";
CHAR_NAME_RESERVED = "此名字无法使用";
CHAR_NAME_THREE_CONSECUTIVE = "同一字符不能连续使用三次";
CHAR_NAME_TOO_LONG = "名字不能超过12个英文字符或6个汉字";
CHAR_NAME_TOO_SHORT = "名字必须包括至少2个字符";
CHAR_RENAME_DESCRIPTION = "您必须修改角色名字";
CHAR_RENAME_FAILED = "重命名失败";
CHAR_RENAME_INSTRUCTIONS = "请输入一个新名字";
CHAR_RENAME_IN_PROGRESS = "正在重命名……";
CHOOSE_CLASS = "选择您的职业：";
CHOOSE_GENDER = "选择您的性别：";
CHOOSE_LOCATION = "选择你偏好的地区：";
CHOOSE_LOCATION_DESCRIPTION = "（请选择最接近你所在地区的服务器位置，以获得最佳游戏效果）";
CHOOSE_RACE = "选择您的种族：";
CHOOSE_REALM_STYLE = "选择您的服务器类型：";
CINEMATICS = "片头动画";
CLASS = "职业"; -- -- Generic class label
CLASS_DRUID = "        德鲁伊和自然之间有一种特殊的联系，这个世界与德鲁伊息息相关，所有生生不息的动物也都和德鲁伊心灵相通。他们是天生的变形专家，能够很快通晓野生动物的习性。因此，世上仅存的德鲁伊们都非常机警，喜欢隐居，并很难被发现。少数在世界各地游荡的德鲁伊更近一步加深了这种神秘感。";
CLASS_HUNTER = "        猎人对于世界上的每个角落都了如指掌，他们天生就对所有的生命有着特殊的感觉，可以和野生的动物成为朋友，并将它们驯服成为自己的宠物。另外，天生的敏锐感觉也使得猎人能够成为出类拔萃的追踪者。无论猎人走到哪里，他们都会和肆虐的疾病、野蛮的开采和污染自然的工业化进行抗争。";
CLASS_MAGE = "        法师都是知识渊博、技艺精湛的魔法专家。他们虚弱的体质只是一个表象，因为召唤混乱能量的能力让他们无比强大。一般来说，法师很少进行近身作战。他们都喜欢与敌人保持一定的距离，召唤魔物或者使用威力强大的远程魔法来击溃他们。";
CLASS_PALADIN = "        圣骑士们使用圣光的力量治愈创伤，并与邪恶交战。已有一千年传统的德莱尼圣骑士来到艾泽拉斯之后，在联盟中找到了志同道合的伙伴。而血精灵最近也开始运用圣骑士的力量，但是这些精灵却与其他圣骑士截然不同，一心想要让圣光的力量为己所用。";
CLASS_PRIEST = "        牧师为他们的人民指引灵魂的归宿。他们可以利用自己对于精神的独特洞察力来影响他人的内心世界，对其进行鼓舞或恐吓，抚慰或者控制，治疗或者伤害。正像人的内心可以同时包容光明和黑暗一样，牧师也由于坚定虔诚的信仰而同时获得了创造和毁灭的力量。";
CLASS_ROGUE = "        成功的盗贼总是在可以隐藏行踪的阴影中行动，他们精于使用毒药和暗杀类的武器，潜行和一点点神秘感则是盗贼的看家本领。他们往往被贵族或者政府所雇佣去窃取财宝或者实施暗杀活动，双方都知道盗贼对主子的忠诚只会持续到合同结束的时候。";
CLASS_SHAMAN = "        萨满祭司和元素之间有着密切的联系。智慧与应变能力的结合让他们成为了各自部族中的领袖和指导者。在战斗中，萨满祭司使用图腾和法术来操纵元素的力量并激发其他同伴们潜在的力量和怒气。萨满祭司充当着自己的种族与他们生存的环境之间的联系者。";
CLASS_WARLOCK = "        术士是恶魔和黑暗法术的操纵者，凭借着恶魔之血赋予他们的邪恶力量，术士能让他们的敌人饱受痛苦的折磨。术士从敌人身上吸取生命的活力，以此来补充那些因为使用黑暗的魔法而损失的能量。除此之外，术士还能召唤和控制各种恐怖的恶魔。他们的邪恶和残忍使其成为最让人恐惧的力量。";
CLASS_WARRIOR = "        战士都在长期的严格训练中磨炼出了无以匹敌的近战技巧。虽然他们来自于不同的种族，但是他们所追求的目标都是要在惨烈的战斗中获得胜利和荣光。许多战士都是雇佣兵，其他的一些则扮演着冒险家和赏金猎人的角色。一个合格的战士应该具有强壮、坚韧和非常好战的特质。";
CLEAR = "清除"; -- Generic 'Clear' button label
CLEARMATRIX = "清除"; -- 'Clear' button label for Matrix Card
CLICK_TO_LAUNCH_ADDON_URL = "点击打开插件网站";
CLIENT_ACCOUNT_MISMATCH = "<html><body><p>您的账号已经激活了进入《魔兽世界：燃烧的远征》的权限，但是您所使用的客户端程序不包含《燃烧的远征》的数据。您必须安装《燃烧的远征》客户端才能正常游戏。更多的信息请查阅：<a href='http://www.wowchina.com/'>www.wowchina.com/</a></p></body></html>";
CLOSE = "关闭";
COMMUNITY_SITE = "官方网站";
COMMUNITY_URL = "http://www.wowchina.com";
CONFIGURE_MODS_FOR = "配置插件给：";
CONFIRM_CHAR_DELETE = "您确认要删除\n|cffffffff%s 等级%d %s|r？";
CONFIRM_CHAR_DELETE_INSTRUCTIONS = "请在框中输入“DELETE”来确认删除。";
CONFIRM_DISABLE_ADDONS = "如果您安装了新版本的插件，就必须重新允许加载这些插件。您确定要禁止所有插件吗？\n\n|cffffffff您可以使用左下角的“插件”按钮来选择加载哪些插件。|r";
CONFIRM_LAUNCH_ADDON_URL = "点击“确定”将切换出游戏画面，并在您的浏览器中打开以下链接：\n%s";
CONFIRM_LOAD_ADDONS = "如果您不升级插件版本的话，游戏可能无法正常运行。您确定要加载所有插件吗？\n\n|cffffffff您可以使用左下角的“插件”按钮来选择加载哪些插件。|r";
CONNECTION_HELP_FRAME_TITLE = "连接帮助";
CONTEST_FRAME_TITLE = "竞赛规则";
CONTEST_NOTICE = "竞赛规则已变更。请在接受协议之前阅读改动的部分。";
CREATE_ACCOUNT = "创建账号";
CREATE_CHARACTER = "创建角色";
CREATE_NEW_CHARACTER = "创建新角色";
CREDITS = "制作人员";
CREDITS_WOW_BC = "燃烧的远征制作人员";
CREDITS_WOW_CLASSIC = "魔兽世界制作人员";
CRIT = "CRIT"; -- G-15 Abbriviation for 'Critical' as in Critical strike chance (melee)
CSTATUS_AUTHENTICATING = "正在认证";
CSTATUS_CONNECTING = "正在和服务器连接……";
CSTATUS_NEGOTIATING_SECURITY = "正在验证安全性";
CSTATUS_NEGOTIATION_COMPLETE = "安全性验证完毕";
CSTATUS_NEGOTIATION_FAILED = "安全性验证失败";
CUSTOMIZE_CHARACTER = "自定义角色：";
DAYS_ABBR_P1 = "天";
DAYS_ABBR = "天";
DEBUG_BUILD = "调试";
DECLINE = "拒绝"; -- Generic decline
DEFENSE = "DEF %d"; -- G-15 Abbribiation for Defense
DELETE_CHARACTER = "删除角色";
DELETE_CONFIRM_STRING = "DELETE";
DISABLE_ADDONS = "禁止";
DISABLE_ALL_ADDONS = "全部禁用";
DISCONNECTED = "已从服务器断开";
DMG = "伤害"; -- G-15 Abbriviation for 'Damage'
DODGE = "DODGE %.2f"; -- G-15 Dodge
DOWNLOADING_UPDATE = "正在下载更新";
DOWNLOAD_SUCCESSFUL = "需要升级补丁";
DOWNLOAD_SUCCESSFUL_TEXT = "请按下重新启动按钮以退出魔兽世界\n并下载升级文件。";
DPS = "DPS"; -- G-15 Abbriviation for 'Damage Per Second'
DURABILITY = "耐久%d"; -- G-15 Abbriviation for durability
ENABLED_FOR_SOME = "该插件只对某些角色启用。";
ENABLE_ALL_ADDONS = "全部启用";
ENTER_PIN_NUMBER = "请输入您的PIN码";
ENTER_WORLD = "进入魔兽世界";
EULA_FRAME_TITLE = "最终用户许可协议";
EULA_NOTICE = "最终用户许可协议已经发生了更改。请向下翻页并阅读更改的部分，然后再点击接受协议按钮。";
EXIT_GAME = "退出游戏";
FACIAL_HAIR_EARRINGS = "耳环";
FACIAL_HAIR_FEATURES = "特征";
FACIAL_HAIR_HAIR = "头发";
FACIAL_HAIR_HORNS = "犄角形状";
FACIAL_HAIR_MARKINGS = "面纹";
FACIAL_HAIR_NORMAL = "胡须";
FACIAL_HAIR_PIERCINGS = "刺环";
FACIAL_HAIR_TUSKS = "獠牙";
FACTION = "阵营"; -- -- Generic Faction label
FACTION_INFO_ALLIANCE = "        联盟由五个种族组成：高贵的人类，勇敢的矮人，神秘的暗夜精灵，机灵的侏儒，以及荣耀的德莱尼。由于都对世界上的各种邪恶势力深恶痛绝，他们就联合起来，为了重建这个饱受战争创伤的世界而努力。";
FACTION_INFO_HORDE = "        部落由五个种族组成：野蛮的兽人，阴暗的亡灵，高尚的牛头人，敏捷的巨魔，以及急躁的血精灵。这些种族都有着为数众多的敌人，为了让自己能在这个世界上继续生存，他们结成了一个强大的同盟。";
FEMALE = "女性";
FRIENDS = "好友";
GAMETYPE_NORMAL = "普通";
GAMETYPE_PVE = "普通";
GAMETYPE_PVE_TEXT = "这些服务器的重点内容在于探索以及与怪物作战，你可以选择是否与敌对阵营的玩家开战。";
GAMETYPE_PVP = "玩家对玩家作战 |cffff0000(PVP)|r";
GAMETYPE_PVP_TEXT = "这些服务器的重点在于玩家之间的战斗。你随时都有可能被敌对阵营的玩家攻击，新手区域和主城除外。";
GAMETYPE_RP = "角色扮演 |cff00ff00(RP)|r";
GAMETYPE_RPPVP = "角色扮演PvP |cffff0000(RPPVP)|r";
GAMETYPE_RPPVP_TEXT = "这些服务器有严格的命名限制和行为规则，适合那些喜欢在游戏世界中扮演虚拟角色的玩家。同时，您也随时有可能在除了起始区域和城镇之外的任何地方遭到对立阵营玩家的攻击。";
GAMETYPE_RP_TEXT = "这些服务器有严格的命名限制和行为规则，适合那些喜欢在游戏世界中扮演虚拟角色的玩家。";
GAME_SERVER_LOGIN = "正在登录游戏服务器";
GAME_UPDATES = "游戏升级";
HAIR_HORNS_COLOR = "犄角颜色";
HAIR_HORNS_STYLE = "犄角形状";
HAIR_NORMAL_COLOR = "发色";
HAIR_NORMAL_STYLE = "发型";
HARDWARE_SURVEY_AGREE = "我同意";
HARDWARE_SURVEY_DISAGREE = "我不同意";
HARDWARE_SURVEY_TITLE = "硬件调查说明";
HELP = "帮助";
HIT = "HIT %d"; -- G-15
HORDE = "部落";
HOURS_ABBR_P1 = "小时";
HOURS_ABBR = "小时";
IDLE_LOGOUT_WARNING = "你很快就将登出游戏";
INT = "智力"; -- G-15 Abbrivation for 'Intellect'
LATEST_EULA_URL = "http://www.wowchina.com/eula.html";
LATEST_TOS_URL = "http://www.wowchina.com/tos.html";
LAUNCH_FAILED = "无法启动魔兽世界";
LAUNCH_MAC_SYSTEM_REQUIRED = "魔兽世界需要Mac OS X %s才能正常运行。";
LAUNCH_QUICKTIME_REQUIRED = "魔兽世界需要QuickTime %s才能正常运行。";
LAUNCH_USE_SOFTWARE_UPDATE = "请升级您的系统软件。"; -- This string is Mac specific.  The updater is called "Sofware Update"
LAUNCH_VIDEO_CARD_UNSUPPORTED = "魔兽世界无法在您的显卡下运行。";
LEVEL = "等级"; -- Level of a monster, character or item
LOAD_ADDONS = "全部加载";
LOAD_FULL = "满";
LOAD_HIGH = "高";
LOAD_LOW = "低";
LOAD_MEDIUM = "中";
LOAD_NEW = "新";
LOAD_RECOMMENDED = "推荐";
LOGIN = "登录";
LOGIN_ALREADYONLINE = "您的账号已经在线。请确认没有其他人正在使用这个账号，然后再次尝试连接。";
LOGIN_BADVERSION = "无法验证游戏版本，这可能是由于文件已被破坏所致。请访问www.wowchina.com/以获取更多信息。";
LOGIN_BAD_SERVER_PROOF = "服务器校验出错";
LOGIN_BAD_SERVER_RECODE_PROOF = "重编码验证失败";
LOGIN_BANNED = "该魔兽世界账号已被冻结，无法继续使用！请检查该账号注册时所使用的电子邮件地址，或拨打客服电话021-51189999获取更多信息。"; -- This is the error message players get when trying to log in with a banned account.
LOGIN_DBBUSY = "现在无法登录魔兽世界，请稍候再试。";
LOGIN_ENTER_NAME = "请输入您的用户名。";
LOGIN_ENTER_PASSWORD = "请输入您的密码。";
LOGIN_ERROR = "发生错误";
LOGIN_FAILED = "连接失败";
LOGIN_INCORRECT_PASSWORD = "密码错误";
LOGIN_INVALID_CHALLENGE_MESSAGE = "无效的账号";
LOGIN_INVALID_PROOF_MESSAGE = "无效的校验信息";
LOGIN_INVALID_RECODE_MESSAGE = "无效的重编码信息";
LOGIN_NOTIME = "您的预付时间已经用尽，请充值之后继续游戏";
LOGIN_PARENTALCONTROL = "该账号已被账号冷冻器锁定。请访问http://www.wowchina.com获得更多信息。";
LOGIN_SERVER_DOWN = "登录服务器无法连接";
LOGIN_SRP_ERROR = "认证错误";
LOGIN_STATE_AUTHENTICATED = "连接成功！";
LOGIN_STATE_AUTHENTICATING = "正在认证";
LOGIN_STATE_CHECKINGVERSIONS = "正在验证版本";
LOGIN_STATE_CONNECTING = "正在连接";
LOGIN_STATE_DOWNLOADFILE = "正在下载";
LOGIN_STATE_HANDSHAKING = "正在与服务器交换数据";
LOGIN_STATE_INITIALIZED = "初始化完成";
LOGIN_STATE_SURVEY = "正在提交非隐私系统信息";
LOGIN_SUSPENDED = "该魔兽世界账号已被暂时冻结，目前无法使用！请检查该账号注册时所使用的电子邮件地址，或者拨打客服电话021-51189999获取更多信息。"; -- This is the error message a player receives when trying to log in with a suspended account.
LOGIN_UNKNOWN_ACCOUNT = "您输入的账号或密码错误，也可能由于您的账号已被安全锁锁定，请访问账号管理页面解锁后重新登陆！如果您发现账号被盗，推荐您立即使用账号安全锁锁定账号以减少您的损失！";
LOGIN_UNKNOWN_ACCOUNT_CALL = "请拨打客服电话021-51189999";
LOGIN_UNKNOWN_ACCOUNT_PIN = "您输入的账号名、账号密码或PIN码错误，也可能由于您的账号已被安全锁锁定，请访问账号管理页面解锁后重新登陆！如果您发现账号被盗，推荐您立即使用账号安全锁锁定账号以减少您的损失！";
MALE = "男性";
MANAGE_ACCOUNT = "账号管理";
MELEE_CRIT = "CRIT %.2f"; -- G-15 Abbriviation for Critical (as in melee critical strike)
MENU_ABOUT = "关于魔兽世界…";
MENU_EDIT = "编辑";
MENU_EDIT_COPY = "复制";
MENU_EDIT_CUT = "剪切";
MENU_EDIT_PASTE = "粘贴";
MENU_EDIT_SELECT_ALL = "全选";
MENU_EDIT_UNDO = "撤消";
MENU_SWITCH_TO_FULLSCREEN = "切换到全屏幕模式";
MINUTES = "%d分";
MINUTES_ABBR = "分";
MINUTES_ABBR_P1 = "分";
NAME = "名字";
NAME_AND_REST_STATE = "%s - %s"; -- Name - rest state
NEWS = "新闻";
NEW_REALM = "新";
NO = "否";
NONE_CAPS = "无"; -- "None", in all capitals
NORMAL_BUILD = "版本";
OKAY = "确定"; -- Generic "okay"
OPTIONS = "选项";
OUTBID_ON_SHORT = "竞标%s失败";
PARRY = "PARRY %.2f"; -- G-15
PASSWORD = "账号密码";
PATCH_FAILED_DISK_FULL = "没有足够的硬盘空间下载补丁。请确保有%dM的可用空间，然后重试。请注意，安装补丁还需要更多的可用空间。";
PATCH_FAILED_MESSAGE = "无法更新补丁，请稍候再试。如果问题继续存在，您可能需要进行重新安装或者和技术支持联系。";
PENETRATION = "PENET %d"; -- G-15 Abbriviation for Spell Penetration
POWER = "PWR %d"; -- G-15 Abbriviation for Power
PVP_PARENTHESES = "(PVP)";
QUEUE_NAME_TIME_LEFT = "%s已满\n队列位置：%d\n预计时间：%d分钟";
QUEUE_NAME_TIME_LEFT_SECONDS = "%s已满\n队列位置：%d\n预计时间：< 1分钟";
QUEUE_NAME_TIME_LEFT_UNKNOWN = "%s已满\n队列位置：%d\n预计时间：正在估算…";
QUEUE_TIME_LEFT = "服务器已满\n您在队列中的位置：%d\n预计等待时间：%d分钟";
QUEUE_TIME_LEFT_SECONDS = "服务器已满\n您在队列中的位置：%d\n预计等待时间：< 1分钟";
QUEUE_TIME_LEFT_UNKNOWN = "服务器已满\n在队列中的位置：%d\n预计剩余时间：正在计算…";
QUIT = "退出";
RACE = "种族"; -- -- Generic race label
RACE_INFO_BLOODELF = "        很久以前，被流放的高等精灵建立了奎尔萨拉斯王国，并制造了一座被称为太阳之井的魔法喷泉。虽然精灵们从太阳之井获得了强大的力量，但他们也变得日益依赖它。许多年后，天灾军团摧毁了太阳之井，杀死了大部分高等精灵。现在，幸存者们开始称自己为血精灵，并努力重建奎尔萨拉斯，同时寻找着新的魔法源泉，以满足他们对于魔法的渴望。";
RACE_INFO_DRAENEI = "        高贵的德莱尼人从他们生活着的阿古斯世界逃出来之后，被燃烧军团追杀了数不清的岁月，最终在一个遥远的星球定居。他们与这个世界的原住民——信奉萨满教义的兽人和平相处，并给这里起名为德拉诺。在兽人被燃烧军团腐蚀而变得嗜血好战之后，德莱尼人几乎遭到了灭顶之灾。一部分幸存者逃到了艾泽拉斯，并在这里找到了共同对抗燃烧军团的盟友。";
RACE_INFO_DWARF = "        很久以来，矮人只关心深埋在地底的财富。后来在一些被发掘出来的文献上记录着：某个神一般的种族创造了矮人，并赋予他们特殊的能力。为了对自己种族的起源有更多的了解，矮人们开始全力挖掘失落的神器，搜集远古的知识。今天，矮人的考古学家已经遍布了世界各地。";
RACE_INFO_GNOME = "        虽然生活在卡兹莫丹的侏儒身材都很矮小，但他们还是凭借超群的智慧在世界上扮演着举足轻重的角色。他们的地下王国诺莫瑞根一度被认为是蒸汽动力科技造就的奇迹。但是，由于石颚怪的大举入侵，这座城市最终还是陷落了。现在痛失家园的侏儒们在矮人的领地内四处流浪，尽可能地为他们的盟友提供援助。";
RACE_INFO_HUMAN = "        人类是个年轻而多才多艺的种族。无论是在战斗技巧、制造技术还是操控魔法方面，人类都有着很高的造诣。勇猛和乐观的天性使人类建造了许多世界上最伟大的王国。在这个动乱的时代，经历了世代纷争的人类正在努力恢复昔日的辉煌，创造光明的未来。";
RACE_INFO_NIGHTELF = "        一万年前，暗夜精灵就已经建立了一个庞大的帝国，但是他们无节制地滥用魔法，最终导致了帝国的毁灭。幸存的暗夜精灵怀着悲伤重新回到了森林中，过起了与世隔绝的隐居生活，直到他们过去的敌人燃烧军团重新来到这个世界。现在，别无选择的暗夜精灵重新开始和外界接触，为了自己的种族能在这个新的世界中生存下去而战斗着。";
RACE_INFO_ORC = "        兽人原本居住在德拉诺世界，过着信仰萨满教的和平生活。后来兽人被燃烧军团奴役，与艾泽拉斯的人类进行了惨烈的战争。多年之后，兽人最终摆脱了恶魔的控制并重新获得了自由。今天，他们为了荣誉和尊严，与一切憎恨和羞辱他们的敌人作战。";
RACE_INFO_SCOURGE = "        在摆脱了巫妖王的铁腕统治之后，由女妖之王希尔瓦娜斯领导的被遗忘者开始找寻新的自由，并渴望对巫妖王的天灾军团进行复仇。当然，想要从这个世界上彻底驱逐一切亡灵的人类也是他们不共戴天的敌人。被遗忘者对他们的盟友也毫不关心，因为对他们来说，加入部落只是为了让他们黑暗而邪恶的计划更进一步的阶梯。";
RACE_INFO_TAUREN = "        牛头人一直以来都在为了自然的平衡而努力，并时刻遵循着他们所信仰的女神：大地母亲的意愿。在邪恶的半人马最近发动的一次突袭下，牛头人的种族险些被彻底灭亡，兽人及时伸出的援手让他们最终击败了入侵者。为了对兽人表示感谢，牛头人加入了部落，这近一步巩固了两个种族之间的友谊。";
RACE_INFO_TROLL = "        暗矛部落的巨魔原本居住在荆棘谷的丛林中，但是由于不同种族之间的连年征战而被迫流离失所。最终这些巨魔与兽人成为了朋友，年轻的兽人酋长萨尔成功地说服了巨魔跟随他一起来到卡利姆多大陆。虽然巨魔继承了他们种族的黑暗本性，但是部落中的其他种族仍然对他们表示出了尊重和敬意。";
RACIAL_ABILITIES = "种族能力";
RANDOMIZE = "随机选择";
REALMLIST_NUMCHARACTERS_TOOLTIP = "您在这个服务器上\n创建的角色数量。";
REALMLIST_POPULATION_TOOLTIP = "标有“推荐”服务器可以使您获得最佳的游戏体验。\n标有“满”的服务器玩家人数偏多，您可能经常\n需要排队等待进入服务器。";
REALMLIST_REALMNAME_TOOLTIP = "请确认您的朋友们在哪个服务器上玩！";
REALMLIST_TYPE_TOOLTIP = "普通 = 该服务器无特殊规则。\nPvP = 玩家对玩家作战。\nRP = 角色扮演服务器。\nRPPvP = 玩家对玩家作战的角色扮演服务器。";
REALM_CHARACTERS = "角色";
REALM_DESCRIPTION = "请选择一个服务器";
REALM_DESCRIPTION_TEXT = "你可以与同一个服务器内的所有玩家进行互动，但是无法与其它服务器中的玩家互动。你的角色不能在服务器间移动。服务器有地区和类型的差异。";
REALM_DOWN = "离线";
REALM_INFO_TEMPLATE = "%-32.32s %4d";
REALM_IS_FULL_WARNING = "您所选择的服务器负载较高，可能有时会需要排队等待进入游戏。建议您考虑选择一个负载较低的服务器。\n\n您确定要选择这个服务器吗？";
REALM_LIST_FAILED = "无法连接服务器列表服务器";
REALM_LIST_INVALID = "非法的服务器列表";
REALM_LIST_IN_PROGRESS = "正在刷新服务器列表";
REALM_LIST_REALM_NOT_FOUND = "您选择的服务器目前无法连接，请使用“改变服务器”按钮来选择其它的服务器。访问www.wowchina.com可以获得当前服务器的状态信息。";
REALM_LIST_SUCCESS = "服务器列表刷新完毕";
REALM_LOAD = "服务器负载";
REALM_LOCKED = "已锁定";
REALM_NAME = "服务器名称";
REALM_TYPE = "类型";
REGEN = "REGEN %.0f"; -- G-15 Abbriviation for Mana Regeneration
RELEASE_BUILD = "正式版本";
RESILIENCE = "RESIL %d"; -- G-15 Abbriviation for Resilience
RESPONSE_CANCELLED = "已取消";
RESPONSE_CONNECTED = "已经连接";
RESPONSE_DISCONNECTED = "已从服务器断开";
RESPONSE_FAILED_TO_CONNECT = "无法连接。请确保您的计算机已经连接到互联网，且没有使用拦截数据传输的防火墙程序。请参考www.wowchina.com/support以获取更多信息。";
RESPONSE_FAILURE = "失败";
RESPONSE_SUCCESS = "成功";
RESPONSE_VERSION_MISMATCH = "错误的客户端版本";
RESTART = "重新启动";
RETURN_TO_LOGIN = "返回登录界面";
RPPVP_PARENTHESES = "(RPPVP)";
RP_PARENTHESES = "(RP)";
SAVE_ACCOUNT_NAME = "记住账号名";
SCANDLL_BUTTON_CONTINUEANYWAY = "继续进入游戏"; -- Caption of button to run WoW even though downloading Scan.dll failed
SCANDLL_BUTTON_MOREINFO = "更多信息"; -- Caption of button to see more information on the web site about a hack or Trojan that was found
SCANDLL_MESSAGE_DOWNLOADING = "[TEMPORARY] Downloading Blizzard Scan"; -- Message shown while downloading Scan.dll
SCANDLL_MESSAGE_ERROR = "[TEMPORARY] |cFFFF0000Blizzard Scan failed to complete|r\n\nNEED WORDING"; -- Message to display when Scan.dll could not be loaded for some reason
SCANDLL_MESSAGE_HACK = "<html><body><p>在您的系统中检测出了\"%1$s\"，运行这个程序有可能损害您的系统安全性，并威胁到您的魔兽世界账号安全。我们强烈建议您在进入游戏之前解决此问题。</p><p>更多信息请<a href='%2$s'>查阅这里</a></p></body></html>"; -- Message displayed when a hack is discovered by Scan.dll.  %s contains hack name
SCANDLL_MESSAGE_HACKFOUND_CONFIRM = "<html><body><p>再次向您强调：在您的系统中检测出了\"%1$s\"，运行这个程序有可能损害您的系统安全性，并威胁到您的魔兽世界账号安全。我们强烈建议您在进入游戏之前解决此问题。更多信息请<a href='%2$s'>查阅这里</a></p></body></html>";
SCANDLL_MESSAGE_HACKNOCONTINUE = "<html><body><p>在您的系统中检测出了\"%1$s\"，运行这个程序有可能损害您的系统安全性，并且可能违反了《魔兽世界最终用户许可协议》。您必须重新启动计算机并确保该程序不再运行才能继续游戏。</p><p>更多信息请<a href='%2$s'>查阅这里</a></p></body></html>";
SCANDLL_MESSAGE_SCANNING = "[TEMPORARY] Scanning for Trojans"; -- Message shown while running Scan.dll
SCANDLL_MESSAGE_TROJAN = "<html><body><p>在您的系统中检测出了\"%1$s\"，运行这个程序有可能损害您的系统安全性，并威胁到您的魔兽世界账号安全。我们强烈建议您在进入游戏之前解决此问题。</p><p>更多信息请<a href='%2$s'>查阅这里</a></p></body></html>"; -- Message displayed when a Trojan is discovered by Scan.dll.  %s contains Trojan name
SCANDLL_MESSAGE_TROJANFOUND_CONFIRM = "<html><body><p>再次向您强调：在您的系统中检测出了\"%1$s\"，运行这个程序有可能损害您的系统安全性，并威胁到您的魔兽世界账号安全。我们强烈建议您在进入游戏之前解决此问题。更多信息请<a href='%2$s'>查阅这里</a></p></body></html>";
SCANDLL_URL_HACK = "http://www.blizzard.com/support/wow/?id=aww01905p"; -- URL to which the user is sent when a hack is detected by Scan.dll
SCANDLL_URL_LAUNCHER_TXT = "http://launcher.wowchina.com/scan/Launcher.txt"; -- URL to use to download Launcher.txt
SCANDLL_URL_TROJAN = "http://www.blizzard.com/support/wow/?id=aww01906p"; -- URL to which the user is sent when a Trojan is detected by Scan.dll
SCANDLL_URL_WIN32_SCAN_DLL = "http://launcher.wowchina.com/scan/Scan.dll"; -- URL to use to download PC Scan.dll
SCANNING_NOTICE = "扫描协议已有变动。请在接受协议之前阅读变动的部分。";
SCAN_FRAME_TITLE = "扫描协议";
SECONDS = "%d秒";
SECONDS_ABBR = "秒";
SECONDS_ABBR_P1 = "秒";
SECURITYMATRIX_DIRECTIONS = "您必须输入密码保护卡上的指定数字才能登录游戏。";
SECURITYMATRIX_ENTER_CELL = "请输入|cFF00FF00%s%s|r格中的数字，然后点击确定按钮。如果您不慎输入了错误的数字，请点击清除按钮。";
SELECT_CHARACTER = "选择角色";
SELECT_RACE = "选择您的种族";
SERVER_ALERT_BUTTON_TEXT = "更多信息";
SERVER_ALERT_TITLE = "系统公告";
SERVER_ALERT_URL = "http://launcher.worldofwarcraft.com/chinaalert";
SERVER_DOWN = "服务器无法连接";
SERVER_SELECTION = "服务器选择";
SERVER_SPLIT = "This realm has exceeded maximum capacity, and will be undergoing a realm split with players divided between two new realms. You will be able to select which of the two new realms you prefer up until |cffffffff%s|r when the split lockout occurs. If you do not make a selection, you will be assigned to one of the new realms. For more information, visit www.worldofwarcraft.com.\n\nPlease select your new realm preference below. You may change your selection at any time until the lockout date.";
SERVER_SPLIT_BUTTON = "服务器分割";
SERVER_SPLIT_CHOOSE_BY = "Choose by:";
SERVER_SPLIT_CURRENT_CHOICE = "当前选择：\n%s";
SERVER_SPLIT_DONT_CHANGE = "清除选择";
SERVER_SPLIT_NOT_NOW = "以后再说";
SERVER_SPLIT_PENDING = "Realm Split Pending...";
SERVER_SPLIT_REALM_CHOICE = "您目前的选择是'|cffffffff%s|r'";
SERVER_SPLIT_SERVER_ONE = "Realm 1";
SERVER_SPLIT_SERVER_TWO = "Realm 2";
SHOW_LAUNCHER = "显示启动器";
SKILLLINES = "技能线路";
SOUL_SHARD = "SHRDS %d"; -- G-15 Abbriviation for Soul Shards (warlock item)
SPD = "SPD %d"; -- G-15 Abbriviation for Speed
SPEED = "SPD %.2f"; -- G-15 Abbriviation for the word Speed
SPI = "精神"; -- G-15 Abbriviation for 'Spirit'
STA = "耐力"; -- G-15 Abbriviation for 'Stamina'
STR = "力量"; -- G-15 Abbriviation for 'Strength'
SUGGESTED_REALM_TEXT = "|cffffffff您被分配到了|r %s |cffffffff服务器。|r";
SUGGEST_REALM = "推荐服务器";
TECH_SUPPORT = "技术支持";
TECH_SUPPORT_URL = "http://www.wowchina.com/support"; -- Tech support web address
TEMP_ARMOR = "- 布甲\n- 皮甲\n- 锁甲";
TEMP_SKILLS = "- 战斗吼叫\n- 急救\n- 作战怒吼";
TEMP_WEAPON = "- 投掷武器\n- 斧\n- 双手斧\n- 剑\n- 双手剑\n- 锤\n- 双手锤\n- 长柄武器\n- 弓";
TOS_ACCEPT = "同意";
TOS_FRAME_TITLE = "服务条款";
TOS_NOTICE = "服务条款已经变更。请在同意本条款前阅读全文。"; -- Notice when the TOS has changed and the player has to re-accept it
UNKNOWN_ZONE = "未知地区";
USE_ENGLISH_SPEECH_PACK = "使用英文语音包";
VERSION_TEMPLATE = "%s %s (%s) (%s)\n%s"; -- Version type(alpha, etc.), version number, internal number, build type(debug, release), date
VIEW_ALL_REALMS = "显示服务器列表";
WEAPONS = "武器";
WEAPON_SKILL = "W.Skill %d"; -- G-15 Abbriviation for Weapon Skill
WEB_SITE = "魔兽世界官方网站";
WHISPER_FROM = "%s的悄悄话";
WORLD_OF_WARCRAFT = "魔兽世界"; -- G-15
YES = "是";
